name: 'Octopus Environment manager'
description: 'Create or delete an environment in octopus'
branding:
  icon: 'truck'
  color: 'green'

inputs:
  environment_name:
    description: 'Name of the environment to create or delete'
    required: true

  delete_environment:
    description: 'Whether or not to delete the environment. Default is `false`'
    required: true
    default: 'false'

  environment_to_copy:
    description: 'Name of the environment from which targets should be added'
    required: true

  octopus_server_url:
    description: 'URL of the Octopus server in the form `http(s)://xxxxx'
    required: true

  octopus_api_key:
    description: ' API key for the Octopus server'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'